version: '3'
name: Mini-IMDB

services:
  db:
    container_name: MySQL
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
